version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: beyond_heaven_api
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    restart: always

  # Frontend Web
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: beyond_heaven_web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
